

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6Imtlc2luaWFAZ21haWwuY29tIiwiaWF0IjoxNzQxNzE4OTkyLCJleHAiOjE3NDE3MjI1OTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.2mZMSamRz2JDbCOBBzI9s04jusx4u3qcJnZn4BaeJrk
{
"users": [
{
    "firstName": "abc4",
    "lastName": "abc4",
    "email": "abc4@gmail.com",
    "password": "@Password123"
}
,
{
    "firstName": "abc5",
    "lastName": "abc5",
    "email": "abc5@gmail.com",
    "password": "@Password123"
}

]}