POST http://localhost:3000/users/create-many
Content-Type: application/json
{
"users": [
{
    "firstName": "abc4",
    "lastName": "abc4",
    "email": "abc4@gmail.com",
    "password": "@Password123"
}
,
{
    "firstName": "abc5",
    "lastName": "abc5",
    "email": "abc5@gmail.com",
    "password": "@Password123"
}

]}